version: '3'
services:

  api:
    image: node
    working_dir: /code
    volumes:
      - type: bind
        source: ./api-achieved
        target: /code

  db:
    image: postgres
    environment: 
      - POSTGRES_USER=achieved
    volumes:
      - "./db/migrations:/docker-entrypoint-initdb.d/:ro"
