services:
  api:
    container_name: test_api
    environment: 
      - PGUSER=achieved
      - PGHOST=db
      - PGPASSWORD=projectpass
      - PGDATABASE=library
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    tty: true
  db:
    container_name: test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
     - POSTGRES_DB=library
     - POSTGRES_PASSWORD=projectpass
volumes:
  test_db:
networks: 
  default:
    name: test
